apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: my-kafka
    meta.helm.sh/release-namespace: kafkatest
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/instance: my-kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-0.21.2
  name: my-kafka-headless
  selfLink: /api/v1/namespaces/kafkatest/services/my-kafka-headless
spec:
  clusterIP: None
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/instance: my-kafka
    app.kubernetes.io/name: kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
