apiVersion: v1
kind: Pod
metadata:
    name: testclient
    namespace: kafkatest
spec:
    containers:
    - name: kafka
      image: confluentinc/cp-kafka
      command:
        - sh
        - -c
        - "exec tail -f /dev/null"
